apiVersion: apps/v1
kind: Deployment
metadata:
  name: motor-transferencia-dep
  labels:
    app: motor-financeiro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: motor-financeiro
  template:
    metadata:
      labels:
        app: motor-financeiro
    spec:
      containers:
        - name: motor-app
          image: motor-transferencia:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/banco_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123"