# 1. Conexão com o PostgreSQL Sénior
spring.datasource.url=jdbc:postgresql://localhost:5432/banco_db
spring.datasource.username=root
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081

# 2. Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. Forçar a Execução do data.sql (A Solução do Falso Zero)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# 4. Configurações do Kafka (Modo KRaft)
spring.kafka.bootstrap-servers=${KAFKA_URL:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# 5. Configurações do Redis (Cache e Idempotência)
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379

# 6. Observabilidade e Identificação
spring.application.name=motor-app
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}

# ----------------------------------------------------
# CONFIGURAÇÕES DO CIRCUIT BREAKER (RESILIENCE4J)
# ----------------------------------------------------

api.security.token.secret=${JWT_SECRET:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30}

# Analisa as últimas 10 chamadas
resilience4j.circuitbreaker.instances.extratoCB.sliding-window-size=10
# Se 50% dessas chamadas falharem, ABRE O CIRCUITO!
resilience4j.circuitbreaker.instances.extratoCB.failure-rate-threshold=50
# Fica aberto (bloqueado) por 10 segundos para o banco de dados "respirar"
resilience4j.circuitbreaker.instances.extratoCB.wait-duration-in-open-state=10s
# Depois de 10s, deixa passar 3 chamadas para testar se o banco já recuperou
resilience4j.circuitbreaker.instances.extratoCB.permitted-number-of-calls-in-half-open-state=3