# ==========================================
# 1. CONEXÃO COM A BASE DE DADOS (NEON)
# ==========================================
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/banco_db}
spring.datasource.username=${DATABASE_USER:root}
spring.datasource.password=${DATABASE_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver

# O Render define a porta automaticamente
server.port=${PORT:8081}

# ==========================================
# 2. CONFIGURAÇÕES DO HIBERNATE (JPA)
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# ==========================================
# 3. CONFIGURAÇÕES DO KAFKA (CONFLUENT CLOUD)
# ==========================================
spring.kafka.bootstrap-servers=${KAFKA_URL:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Protocolo de segurança exigido pela Confluent Cloud
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=${KAFKA_SASL_MECHANISM:PLAIN}
spring.kafka.properties.sasl.jaas.config=${KAFKA_JAAS_CONFIG:}

# ==========================================
# 4. SEGURANÇA E JWT
# ==========================================
api.security.token.secret=${JWT_SECRET:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30}

# ==========================================
# 5. OBSERVABILIDADE
# ==========================================
spring.application.name=motor-app
management.endpoints.web.exposure.include=health,info,prometheus

# ==========================================
# 6. CIRCUIT BREAKER (RESILIENCE4J)
# ==========================================
resilience4j.circuitbreaker.instances.extratoCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.extratoCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.extratoCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.extratoCB.permitted-number-of-calls-in-half-open-state=3