name: BazaBank CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-analyze:
    name: 🧪 Testes e Validação
    runs-on: ubuntu-latest
    
    # Esta configuração diz ao Github que todos os comandos 'run' 
    # deste job devem acontecer dentro da pasta do backend!
    defaults:
      run:
        working-directory: ./motor-core-java

    steps:
      - name: 📥 Baixar o código do repositório
        uses: actions/checkout@v4

      - name: ☕ Configurar o Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: 🚀 Executar Testes Unitários e de Integração (Testcontainers)
        run: mvn clean verify

  build-and-push-aws:
    name: 🐳 Build e Deploy AWS ECR
    needs: test-and-analyze
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' 
    
    # Aplicamos a mesma regra para o build
    defaults:
      run:
        working-directory: ./motor-core-java

    steps:
      - name: 📥 Baixar o código do repositório
        uses: actions/checkout@v4

      - name: ☕ Configurar o Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: 🔨 Compilar o App (Sem rodar testes de novo)
        run: mvn clean package -DskipTests

      - name: 🔐 Configurar Credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🔑 Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 🐳 Build e Push da Imagem para o ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: motor-transferencia
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Como o working-directory está configurado, ele vai achar o Dockerfile corretamente
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags