name: BazaBank CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-analyze:
    name: 🧪 Testes e Validação
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Baixar o código do repositório
        uses: actions/checkout@v4

      - name: ☕ Configurar o Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Corrigido para bater com o pom.xml
          distribution: 'temurin'
          cache: 'maven'

      - name: 🚀 Executar Testes Unitários e de Integração (Testcontainers)
        # Retirado o -DskipTests. O GitHub Actions rodará o Docker em background para os Testcontainers!
        run: mvn clean verify

  build-and-push-aws:
    name: 🐳 Build e Deploy AWS ECR
    needs: test-and-analyze # Esta etapa só roda se os testes passarem!
    runs-on: ubuntu-latest
    # Só faz push para a AWS se for um merge/push na main (não faz deploy de Pull Requests)
    if: github.ref == 'refs/heads/main' 
    steps:
      - name: 📥 Baixar o código do repositório
        uses: actions/checkout@v4

      - name: ☕ Configurar o Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: 🔨 Compilar o App (Sem rodar testes de novo)
        run: mvn clean package -DskipTests

      - name: 🔐 Configurar Credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🔑 Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 🐳 Build e Push da Imagem para o ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: motor-transferencia
          IMAGE_TAG: ${{ github.sha }} # Prática Sênior: Usar o hash do commit como tag, além do 'latest'
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags